# This workflow will build a package using Maven and then publishCommand it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    environment: playground
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
        ref: main

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      working-directory: remote-components-aem-package
      run: |
        git config --local user.name ethereal-nexus-github-actions
        git config --local user.email ethereal-nexus-github-actions@diconium.com
        mvn -B release:prepare release:perform --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Publish to GitHub Packages Apache Maven
      working-directory: remote-components-aem-package
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
